### ISSUE TITLE
Naming!

### ISSUE THREAD

**Issue by krainboltgreene** [marvinmarnold/windjs#1]
We should think about naming.
- Bluetooth is a link layer protocol
- wind, communicating via bluetooth broadcasted metadata is a internet layer protocol
- `{...}`, formatting bluetooth metadata, is a transmission layer protocol
- `{...}`, sending and receiving semi-anonymous messages in a plain or encrypted manner, is an application layer protocol.

We need to name the latter two layers. I propose **skaal** for the ALP since skaal means to "toast" or "cheer" and was often used by Vikings, whom the namesake of Bluetooth was attributed to (specifically king Harald Bluetooth). For the TLP I suggest **bark**, because it's cute.

**Comment by marvinmarnold** [comment]
After talking to @n8fr8, it might be a good idea to move this conversation to https://talk.developersquare.net/c/developers-corner/people-powered-nearby-networks as it effects the overall Wind Farm and is not necessarily specific to this implementation.

**Comment by krainboltgreene** [comment]
Sure that makes sense. By the way, do you have an email I can use to get in contact?

**Comment by krainboltgreene** [comment]
Link: https://talk.developersquare.net/t/protocol-specification-naming/80
